---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-api
  namespace: barata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-api
  template:
    metadata:
      labels:
        app: config-api
    spec:
      containers:
        - name: config-api
          image: baratahunter/config-api:latest
          ports:
            - containerPort: 3000
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: config-api
  namespace: barata
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
  selector:
    app: config-api
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: config-api
  namespace: barata
spec:
  tls:
  - hosts: 
    - config-api.border.berzuk.com
  ingressClassName: nginx
  rules:
  - host: config-api.border.berzuk.com
    http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: config-api
                port:
                  number: 80
