---
- hosts: localhost

  tasks:

  - name: stop existing container
    command: docker container stop config-api-jenkins
    ignore_errors: yes

  - name: remove container
    command: docker container rm config-api-jenkins
    ignore_errors: yes

  - name: remove image
    command: docker image rm baratahunter/config-api
    ignore_errors: yes

  - name: create container
    command: docker container run -d --name config-api-jenkins -p 3000:3000 baratahunter/config-api
